development:
  host: "localhost:3000"
  admin_email: "admin@neiworld.com"
  auto_activate: true

test:
  host: "localhost:3000"
  admin_email: "admin@neiworld.com"
  auto_activate: false

production:
  host: "www.neiworld.com"
  admin_email: "admin@neiworld.com"
  auto_activate: true

